#!/bin/dash

init_notify() {
	user=$(whoami)
	pids=$(pgrep -u $user urxvtd)
	for pid in $pids; do
		# find DBUS session bus for this session
		DBUS_SESSION_BUS_ADDRESS=$(grep -z DBUS_SESSION_BUS_ADDRESS /proc/$pid/environ | sed -e 's/DBUS_SESSION_BUS_ADDRESS=//')
		# use it
		export DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS
	done
}

if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
 init_notify
fi

box=$(find ${HOME}/Mail/GMail/INBOX/new -type f | wc -l)
box2=$(find ${HOME}/Mail/personal/INBOX/new -type f | wc -l)

if [ "${box}" -gt "0" ] ; then 
  if [ "${box2}" -gt "0" ] ; then
    notify-send -t 15000 "Gmail: ${box}/ Personal: ${box2}"
  fi
fi

if [ "${box}" -gt "0" ] ; then
  if [ "${box2}" -eq "0" ] ; then
    notify-send -t 15000 "Gmail: ${box}"
  fi
fi

if [ "${box2}" -gt "0" ] ; then
  if [ "${box}" -eq "0" ] ; then
    notify-send -t 15000 "Personal: ${box2}"
  fi
fi
